
logging_steps: 50
# log_level_replica: info

inf_free: false
model_name_or_path: answerdotai/ModernBERT-base
tokenizer_name: answerdotai/ModernBERT-base
use_l0: false

max_seq_length: 256
train_file: data/msmarco_hard_negatives
data_type: kd
loss_types: [marginmse]
sample_num_one_query: 2
use_in_batch_negatives: false
flops_d_lambda: 6
flops_d_T: 50000
flops_q_lambda: 10
flops_q_T: 50000
flops_d_thresh: 180
flops_q_thresh: 90

output_dir: output/paper/bi/modernbert-base
per_device_eval_batch_size: 50
per_device_train_batch_size: 20

log_level: info
max_steps: 150000
fp16: true
learning_rate: 0.00002
weight_decay: 0.01
lr_scheduler_type: linear
warmup_steps: 6000
save_strategy: steps
save_steps: 150000
dataloader_drop_last: true
max_grad_norm: null
